from typing import Any, Callable, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])

class FastMCP:
    def __init__(self, name: str) -> None: ...
    def tool(self, *, description: str) -> Callable[[_F], _F]: ...
    def run(self) -> None: ...
